url = "https://vra8.lab.sentania.net/"
zone_name = "WLD 1 / lab-vcf-w01-DC"
project_name = "Test Project 3"
insecure = false
priority         = 1
max_instances    = 50
cpu_limit        = 64
memory_limit_mb  = 81920
storage_limit_gb = 81920
description = "This is a project created with TF"
administrators = ["vradmins@int.sentania.net"]
users = ["vrausers@int.sentania.net"]