url = "https://vra8.lab.sentania.net/"
zone_name = "WLD 1 / lab-vcf-w01-DC"
project_name = "Test Project 2"
insecure = false
priority         = 1
max_instances    = 35
cpu_limit        = 32
memory_limit_mb  = 32000
storage_limit_gb = 8192
description = "This is the second project created with TF"
