url = "https://vra8.lab.sentania.net/"
zone_name = "WLD 1 / lab-vcf-w01-DC"
project_name = "Test Project 1"
insecure = false
priority         = 1
max_instances    = 25
cpu_limit        = 32
memory_limit_mb  = 81920
storage_limit_gb = 81920
description = "This is the second project created with TF"
