url = "https://vra8.lab.sentania.net/"
zone_name = "WLD 1 / lab-vcf-w01-DC"
project_name = "Test Project 2"
insecure = false
priority         = 1
max_instances    = 750
cpu_limit        = 96
memory_limit_mb  = 1920
storage_limit_gb = 81920
description = "This is a project created with TF (Test)"
administrators = ["vradmins@int.sentania.net"]
users = ["vrausers@int.sentania.net"]
basename =  "$${resource.name}-$${#####}"
