variable "refresh_token" {}
variable "url" {}
variable "insecure" {}
variable "zone_name" {}
variable "project_name" {}
variable "priority" {}
variable "max_instances" {}
variable "cpu_limit" {}
variable "memory_limit_mb" {}
variable "storage_limit_gb" {}
variable "description" {}
variable "administrators" {}
variable "users" {}
variable "basename" {}
